### PR TITLE
Consistently space the opening and closing comments

### PR DESCRIPTION
**Pull request by chocolateboy**
Add an extra newline between the opening comment and the start of the TOC:

### before

```markdown
<!-- TOC -->
- [foo](#foo)
- [bar](#bar)
- [baz](#baz)
  - [quux](#quux)

<!-- TOC END -->
```

### after

```markdown
<!-- TOC -->

- [foo](#foo)
- [bar](#bar)
- [baz](#baz)
  - [quux](#quux)

<!-- TOC END -->
```

This makes the spacing for the opening comment consistent with the closing comment, and is consistent with other tools, e.g. [doctoc](https://github.com/thlorenz/doctoc) and [markdown-toc](https://github.com/jonschlinkert/markdown-toc) (which preserves newlines).

### CODE REVIEW

**Comment by theogravity** [comment]
Thanks for the contribution. Is the top still valid after the changes, and do the tests pass?

**Comment by chocolateboy** [comment]
Yes, the tests all pass, and it works in my project.

**Comment by theogravity** [comment]
i'll publish in an hour or so thanks

**Comment by theogravity** [comment]
@chocolateboy published under `0.4.0`

I've added you as a collaborator. I'll update the project tonight to auto-publish to npm on commits to master.

**Comment by chocolateboy** [comment]
Thanks! :tada:

**Pull request merged**
