### PR TITLE
Remove dependency on compromised package

### PR DESCRIPTION
**Pull request by chocolateboy**
https://github.com/Marak/colors.js/issues/285

### CODE REVIEW

**Comment by theogravity** [comment]
@chocolateboy can you point me to the repo that @dabh/colors is coming from as npm is down right now? I'd like to verify the modifications (if any at all) to make sure that one comes from a reputable source

**Comment by chocolateboy** [comment]
Yes, sorry. See [here](https://github.com/Marak/colors.js/issues/285#issuecomment-1008212640) ([repo](https://github.com/DABH/colors.js)).

**Comment by theogravity** [comment]
Looks good, thanks!

**Review by theogravity — APPROVED** [review]

**Comment by theogravity** [comment]
Published.

odd, it looks like github or maybe synk switched the default branch?

**Pull request merged**
